### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by harkamals** [duo-labs/cloudmapper#19] opened 2018-02-21 03:20 UTC
redhat 7.3
firefox 59.0b10

**Comment by 0xdabbad00** [comment] 2018-02-21 03:47
Can you look at your Network Monitor view in Firefox?  https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor
See if any of the calls are 404'ing.  The icons are SVG files, so try opening the file directly in Firefox and seeing if your browser supports displaying those.  Ex. https://github.com/duo-labs/cloudmapper/blob/master/web/icons/aws/Compute/Compute_AmazonEC2.svg

**Comment by kpawloski** [comment] 2018-02-21 20:03
I ran into the same problem on a freshly spun up CentOS 7 VM. After restarting the instance, the issue cleared itself up though. Haven't been able to replicate the behavior since.

**Comment by rafarost** [comment] 2018-02-22 18:08
I ran into the same issue. I tried rebooting my VM... did not worked. So I upgraded python to 3.6, created a new environment and it started working again...

**Comment by 0xdabbad00** [comment] 2018-02-22 18:32
@kpawloski and @rafarost Were you each on Firefox as well?  Did the tool bar load?  I'd be interested in seeing a screenshot if anyone duplicates this, and ideally any log messages from the Python webserver (or whatever webserver you use, as it's just static files being hosted), and a screenshot of the developer tools in the browser showing network access.

**Comment by rafarost** [comment] 2018-02-22 18:36
I'm using Chrome. Unfortunately I did not took any screenshot at the time. Like I said, it's working for me now. If it happen again, I will post here. Thanks.

**Comment by 0xdabbad00** [comment] 2018-02-22 18:49
I tried to describe a bit about some of the visual elements.
If the `data.json` file cannot be found (ie. you didn't create it), then the pan and zoom controls will not load and neither will the graph. I suspect this may be the root cause.  I created https://github.com/duo-labs/cloudmapper/issues/39 to add an error message.

<img width="1388" alt="screen shot 2018-02-22 at 11 42 38 am" src="https://user-images.githubusercontent.com/1979334/36557671-29818fda-17c6-11e8-8945-e47314ad9e34.png">

**Comment by kpawloski** [comment] 2018-02-22 20:03
In my case the icons, pan and zone and overview in the lower right loaded just fine using the demo data but the actual graphs in the main area wouldn't show at any zoom level. Was using FireFox. Haven't been able to reproduce the issue since initial run.

**Comment by takuma-watanabe** [comment] 2018-02-23 11:19
responding svg data from web server, its mime type should be " image/svg+xml" instead of "application/octet-stream"

My PR may solve this problem.
Please check #46 .

**Comment by 0xdabbad00** [comment] 2018-03-05 22:22
Someone sent me a screenshot privately, so this bug still exists.  The toolbar icons in the top left were visible, but no icons for the different nodes.  So the cytoscape map showed up, showing the connections and VPCs, but just the SVG's for the nodes themselves were not showing. Odd.

In order to find these icons, I just tell cytoscape to use a `style.json` file: https://github.com/duo-labs/cloudmapper/blob/29abd7f968758631f188dc4b76d4b7bc9307951a/web/js/cloudmap.js#L40

This file then references the .svg's: https://github.com/duo-labs/cloudmapper/blob/29abd7f968758631f188dc4b76d4b7bc9307951a/web/style.json#L92

In the image I saw, the compound nodes had the borders and colorings specified in the style.json file, so the style.json must have been loaded, but just the SVG's did not load.

One possibility is perhaps the webserver was killed, or crashed, after the page was initially loaded, but before the diagram was displayed.

**Comment by 0xdabbad00** [comment] 2018-03-23 19:47
I ended up being on a very slow network today and loaded the demo at https://duo-labs.github.io/cloudmapper/ and experienced this issue.  After waiting a while, the images did eventually load.  So this is one way in which this issue will exhibit itself.

**Comment by 0xdabbad00** [comment] 2019-02-17 02:35
Closing due to staleness. I'm assuming this might have been fixed at some point somehow.

**Closed by 0xdabbad00** 2019-02-17 02:35 UTC
Labels: bug
