### ISSUE TITLE
Duplicate/additional databases

### ISSUE THREAD

**Issue by aioue** [duo-labs/cloudmapper#74] opened 2018-03-14 09:46 UTC
When rendering RDS databases, I am seeing non-multiAZ DBs located in just 1 availability zone, being shown in all AZs.

Eg: here, this DB is only in one subnet, in 1 AZ, but shows up three times in 3 subnets.

![image](https://user-images.githubusercontent.com/1254905/37394684-3e514648-276c-11e8-950f-ffb640ba7dbe.png)

**Comment by 0xdabbad00** [comment] 2018-03-14 14:06
The way CloudMapper's `prepare` phase works is it will find all the regions->VPCs->AZs->subnets->nodes.  You can see where CloudMapper looks for the RDS nodes in a subnet here: https://github.com/duo-labs/cloudmapper/blob/4dfe6d742f2b21e987f0ed262c1023361397b29c/cloudmapper/prepare.py#L268

which calls into this:
https://github.com/duo-labs/cloudmapper/blob/4dfe6d742f2b21e987f0ed262c1023361397b29c/cloudmapper/prepare.py#L111

That call to `get_rds_instances` is what is running some `jq` queries against the `json` files acquired in the `gather` phase, and it matches all RDS instances that have specified the given subnet.

Can you look at your `describe-db-instances.json` file in the region of interest and check that the `rd-rds-euc1-platform-dev` RDS there actually only has one subnet listed?

**Comment by aioue** [comment] 2018-03-16 17:12
`describe-db-instances.json` for the `rds-euc1-platform-dev` RDS has 3 `Active` subnets listed in the `DBSubnetGroup`.

MultiAZ for the RDS is `"MultiAZ": false`. Only 1 instance exists.

**Comment by 0xdabbad00** [comment] 2018-03-16 17:49
Does this mean that the RDS instance only exists in one subnet at a time, but can failover to different subnets?  Do you know how I figure out which subnet the instance for it is currently in?

**Comment by 0xdabbad00** [comment] 2019-05-07 19:10
Closing due to staleness

**Closed by 0xdabbad00** 2019-05-07 19:10 UTC
Labels: bug, map

**Comment by ethanmdavidson** [comment] 2019-08-23 21:37
Don't mean to gravedig, but I'm seeing the same thing. I think the confusion here is that by default RDS will attach a new instance to every subnet in the VPC, even though the instance is only running in one AZ.

see this example output from `aws rds describe-db-instances`:
```
{
    "DBInstances": [
        {
            "DBInstanceIdentifier": "mydatabase",
            "DBInstanceClass": "db.t2.medium",
            "Engine": "sqlserver-ex",
            "DBInstanceStatus": "available",
            "MasterUsername": "xxxxx",
            "Endpoint": {
                "Address": "mydatabase.xxxxxx.us-east-1.rds.amazonaws.com",
                "Port": 1433,
                "HostedZoneId": "Z2R2ITUGPM61AM"
            },
		<snipped>
            "AvailabilityZone": "us-east-1d",
            "DBSubnetGroup": {
                "DBSubnetGroupName": "default-vpc-0e4b2874",
                "DBSubnetGroupDescription": "Created from the RDS Management Console",
                "VpcId": "vpc-0e4b2874",
                "SubnetGroupStatus": "Complete",
                "Subnets": [
                    {
                        "SubnetIdentifier": "subnet-f0adffde",
                        "SubnetAvailabilityZone": {
                            "Name": "us-east-1d"
                        },
                        "SubnetStatus": "Active"
                    },
                    {
                        "SubnetIdentifier": "subnet-e0eee7ef",
                        "SubnetAvailabilityZone": {
                            "Name": "us-east-1f"
                        },
                        "SubnetStatus": "Active"
                    },
                    {
                        "SubnetIdentifier": "subnet-6215f22f",
                        "SubnetAvailabilityZone": {
                            "Name": "us-east-1a"
                        },
                        "SubnetStatus": "Active"
                    },
                    {
                        "SubnetIdentifier": "subnet-3ee6b662",
                        "SubnetAvailabilityZone": {
                            "Name": "us-east-1b"
                        },
                        "SubnetStatus": "Active"
                    },
                    {
                        "SubnetIdentifier": "subnet-ee8add89",
                        "SubnetAvailabilityZone": {
                            "Name": "us-east-1c"
                        },
                        "SubnetStatus": "Active"
                    },
                    {
                        "SubnetIdentifier": "subnet-11df452f",
                        "SubnetAvailabilityZone": {
                            "Name": "us-east-1e"
                        },
                        "SubnetStatus": "Active"
                    }
                ]
            },
            "MultiAZ": false,
            "ReadReplicaDBInstanceIdentifiers": [],
        }
    ]
}
```

You can see that multiple subnets are active, but `MultiAZ` is false and `AvailabilityZone` is "us-east-1d". There is also a `HostedZoneId` in the endpoint which seems like it might be related. 

It seems to me that the expected behavior here would be to display the node only in the AZ where it is actually running. However I'm very new to AWS and don't have a networking background so I don't really understand what it's doing with the subnets, so maybe it is more accurate to display the node in each AZ, even if it doesn't make sense at first glance to noobs like me.

I'm also not sure what the data would look like with a Multi-AZ setup. Presumably, `MultiAZ` would be true, and maybe `AvailabilityZone` would show the AZ in which it is currently running? not sure how the failover instance would show up.
