### ISSUE TITLE
node_data object is always empty in data.json

### ISSUE THREAD

**Issue by ashoksmohanty** [duo-labs/cloudmapper#708] opened 2020-05-28 09:58 UTC
Hi,
I have installed CloudMapper and successfully able to pull audit data. But i can see in below json "node_data":{}" is always empty. Could you please guide me where i did wrong? But in sample link https://duo-labs.github.io/cloudmapper/ node_data is not empty.
        "data": {
            "id": "arn:aws:lambda:us-east-1:122449832:function:demo-inventory-qa-dev-subnet-0c2de33efb6d3",
            "name": "demo-inventory-qa-dev ",
            "type": "lambda",
            "local_id": "arn:aws:lambda:us-east-1: 122449832:function:demo-inventory-qa-dev ",
            **"node_data": {},**
            "parent": "arn:aws::us-east-1: 122449832:subnet/subnet-0c2de33efb6d3"
        }

**Comment by 0xdabbad00** [comment] 2020-05-28 14:49
This is a duplicate of #689.

**Closed by 0xdabbad00** 2020-05-28 14:49 UTC
