### ISSUE TITLE
 AccessDeniedException

### ISSUE THREAD

**Issue by Hindmalti** [duo-labs/cloudmapper#543] opened 2019-09-05 09:20 UTC
Hello ! 
I've got an error : an AccessDeniedException, 
I can't launch the CloudMapper tool because I can't be on the root account of my company, I can only be admin.
I'm in a secondary account, since we are in an organization, we have a master account that is used for billing, the other accounts (prod, nonprod etc) are attached to it.
Is there a way to get around the problem? 
Thank's !

**Comment by 0xdabbad00** [comment] 2019-09-05 13:29
If you have SecurityAudit and ViewOnlyAccess, CloudMapper should work. If you do not have those privileges, the problem is unfortunately outside the scope of what I'm able to support with the tool.

**Comment by 0xdabbad00** [comment] 2019-09-18 03:03
Closing as outside the scope and related to #537

**Closed by 0xdabbad00** 2019-09-18 03:03 UTC
