### ISSUE TITLE
Unable to Generate Report, 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jack-robs** [duo-labs/cloudmapper#536] opened 2019-08-21 19:39 UTC
Hello got the following error, tracking the previous bug report, which it was indicated 'collect' may have not been run first (I ran collect).

Error:
####
python cloudmapper.py report --account <account>
* Getting resource counts
Traceback (most recent call last):
  File "cloudmapper.py", line 72, in <module>
    main()
  File "cloudmapper.py", line 66, in main
    commands[command].run(arguments)
  File "/path/path/networkmap/cloudmapper/commands/report.py", line 461, in run
    report(accounts, config, args)
  File "/path/path/networkmap/cloudmapper/commands/report.py", line 97, in report
    account, args.stats_all_resources
  File "/path/path/networkmap/cloudmapper/shared/common.py", line 280, in get_account_stats
    )["LocationConstraint"]
TypeError: 'NoneType' object is not subscriptable
####

Commands run:
$ (cloudmapper) bash-3.2$ python cloudmapper.py collect --account <account>
(several minutes of console outputs related to my account)
$ (cloudmapper) bash-3.2$ python cloudmapper.py report --account <account>
(that error)

Thanks!

**Comment by jack-robs** [comment] 2019-08-21 19:50
The `collect` step (re-ran it) output the following:
`Failures:
  s3.get_bucket_acl({'Bucket': 'additional-doc'}): An error occurred (AccessDenied) when calling the GetBucketAcl operation: Access Denied
  s3.get_bucket_policy({'Bucket': 'additional-doc'}): An error occurred (AccessDenied) when calling the GetBucketPolicy operation: Access Denied
  s3.get_bucket_logging({'Bucket': 'additional-doc'}): An error occurred (AccessDenied) when calling the GetBucketLogging operation: Access Denied
  s3.get_bucket_location({'Bucket': 'additional-doc'}): An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied
`

Confirmed outside of the venv shell that I could call 
$ aws s3api get-bucket-location --bucket <bucket I have>
-> which output:
{
    "LocationConstraint": null
}

Which per some other docs, seems to indicate null is reported out if the bucket is in us-east-1, which that bucket is.

Is AWS S3 reporting null, and cloudmapper putting in a null value for LocationConstraint perhaps?

**Comment by kmcquade** [comment] 2019-08-21 20:53
Same

**Comment by kmcquade** [comment] 2019-08-21 21:12
@jack-robs I ran into this error for the iam_report command. I solved it by modifying the iam_report.py file at line 84 from this:

```python
        job_id = get_parameter_file(
            region,
            "iam",
            "generate-service-last-accessed-details",
            principal_auth["Arn"],
        )["JobId"]
```

to this:
```python
       try:
          job_id = get_parameter_file(
              region,
              "iam",
              "generate-service-last-accessed-details",
              principal_auth["Arn"],
           )["JobId"]
       except TypeError:
           continue
```

**Comment by 0xdabbad00** [comment] 2019-08-21 22:27
I think there are different issues at play here.

For the problem from @jack-robs, it looks like access is completely denied on a certain bucket. I'm assuming your IAM policy (or SCP or something) must have something like:
```
"Effect": "Deny",
"Action": "*",
"Resource": "arn:aws:s3:::some_bucket"
```

As a result, no data can be collected from it.  CloudMapper makes the assumption that it has all of the privileges granted by `SecurityAudit` and `ViewOnlyAccess`.  If that is not true, then you will run into problems.  As people are focusing more and more on limiting their IAM policies and doing things like applying SCPs that are outside of the control of the account owners, these problems have been popping up.  I worry I'm going to be playing whack-a-mole if I try to account for unique policies people are creating, and believe that these issues are going to be outside of the scope of this project to account for, unless a generic solution arises, or I run into a problem like this myself in an environment and am forced to better handle it.

I think also that when `collect` is run and errors are encountered, I need to record those errors, and somehow force all of the other commands to report those errors encountered, especially in cases of any exceptions like this, as the problem is very likely related to the collection errors.

As for the problem from @kmcquade, I think similarly the file `./account-data/YOUR_ACCOUNT/us-east-1/iam-generate-service-last-accessed-details.json` does not exist or is not formatted correctly, due to some sort of errors on the `collect`.

**Comment by jack-robs** [comment] 2019-08-22 12:27
@0xdabbad00 So I was thinking what you were thinking - my IAM policy for my profile is forbidding me from calling `s3:Action` so cloudmapper, via my profile, couldn't do that as well. However, w/o cloudmapper invovled, I could call that `s3:action`, in that case `get-bucket-location`. So w/ cloudmapper: can't call `get-bucket-location`, without cloudmapper, could call `get-bucket-location`. Is that what you were referring to w/ IAM? 

I'll double check what I have in IAM though, perhaps I can call `s3:get-bucket-location` via my profile, but if cloudmapper is doing its thing via a service role or similar, and I don't have that role giving access to `get-bucket-location`, that would follow. Thanks! Quick response is awesome.

@kmcquade excellent, let me try that as well.

**Comment by jack-robs** [comment] 2019-08-22 14:21
@kmcquade that worked, as far as generating the report, different part of the codebase but same conce.t
@0xdabbad00 not sure if you want a PR though, it generates a 'Critical' output on the localhost/account-data/report:

`{
    "exception": "local variable 'grant' referenced before assignment",
    "traceback": "Traceback (most recent call last):\n  File \"/path/cloudmapper/shared/audit.py\", line 121, in audit_s3_buckets\n    for grant in file_json[\"Grants\"]:\nTypeError: 'NoneType' object is not subscriptable\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/path/cloudmapper/shared/audit.py\", line 978, in audit\n    audit_s3_buckets(findings, region)\n  File \"/path/cloudmapper/shared/audit.py\", line 138, in audit_s3_buckets\n    \"grant\": grant,\nUnboundLocalError: local variable 'grant' referenced before assignment\n"
}`

With the higher level output of `Other issues cannot be checked for until this is fixed.`

I can try to trace through for that error as well, but not sure how much downstream stuff this leads too.

**Comment by 0xdabbad00** [comment] 2019-08-22 14:31
@jack-robs Note that based on your error, CloudMapper is not able to make any of the following calls:
- s3.get_bucket_acl
- s3.get_bucket_policy
- s3.get_bucket_logging
- s3.get_bucket_location

It is showing you a Critical error because things are broken (ie. you lack privileges) in a way that CloudMapper does not understand and thus some of it's checks are not going to work, and problems it would normally detect will be hidden.

It sounds like you may be using the `--profile` option of CloudMapper and that is resulting in your running with different privileges than you would normally.  You should use CloudMapper within an `aws-vault` environment and things will likely go more smoothly for you.

I'm closing this issue as it sounds like the problems you both have run into are outside of the scope of CloudMapper (ie. you have different privileges than what CloudMapper expects to be able to run properly).

**Closed by 0xdabbad00** 2019-08-22 14:31 UTC

**Comment by jack-robs** [comment] 2019-08-22 14:35
Yeah makes sense, I'll try aws-vault.

I'm not tracking on the privileges aspect, given that I can do:

* s3.get_bucket_acl
* s3.get_bucket_policy
* s3.get_bucket_logging
* s3.get_bucket_location

all with my master profile via aws cli (not using cloudmapper), but if cloudmapper isn't reaching back and hitting my .aws/config and .aws/creds on the way to doing this audit, that makes sense as to why it doesn't work for me.
