### ISSUE TITLE
icons do not appear on the webpage

### ISSUE THREAD

**Issue by alanxavier** [duo-labs/cloudmapper#86] opened 2018-05-15 18:46 UTC
I did an install of cloudMapper, when displaying a web page does not appear the icons. ex: ec2, rds
![image](https://user-images.githubusercontent.com/25588902/40077157-25705ddc-5857-11e8-9b07-879dc6029413.png)

**Comment by 0xdabbad00** [comment] 2018-05-15 23:48
Closing as duplicate of #19 . This is normally resolved simply by refreshing the page.  It's unknown still why this happens.

**Closed by 0xdabbad00** 2018-05-15 23:48 UTC

**Comment by alanxavier** [comment] 2018-05-17 14:29
I used nginx and it worked perfectly, thanks.

Good project congratulations.
